// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevicesByIDsAndUser = `-- name: CountDevicesByIDsAndUser :one
SELECT count(*)
FROM devices
WHERE user_id = $1
  AND id = ANY($2::uuid[])
`

type CountDevicesByIDsAndUserParams struct {
	UserID    pgtype.UUID   `json:"user_id"`
	DeviceIds []pgtype.UUID `json:"device_ids"`
}

func (q *Queries) CountDevicesByIDsAndUser(ctx context.Context, arg CountDevicesByIDsAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesByIDsAndUser, arg.UserID, arg.DeviceIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    user_id,
    name,
    device_type,
    firmware_version,
    battery_level,
    is_connected,
    active_eq_profile_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, device_type, firmware_version, battery_level, is_connected, active_eq_profile_id, paired_at, created_at, updated_at
`

type CreateDeviceParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	Name              string      `json:"name"`
	DeviceType        string      `json:"device_type"`
	FirmwareVersion   string      `json:"firmware_version"`
	BatteryLevel      int32       `json:"battery_level"`
	IsConnected       bool        `json:"is_connected"`
	ActiveEqProfileID pgtype.UUID `json:"active_eq_profile_id"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Name,
		arg.DeviceType,
		arg.FirmwareVersion,
		arg.BatteryLevel,
		arg.IsConnected,
		arg.ActiveEqProfileID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.FirmwareVersion,
		&i.BatteryLevel,
		&i.IsConnected,
		&i.ActiveEqProfileID,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices
WHERE id = $1
  AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeviceByIDAndUser = `-- name: GetDeviceByIDAndUser :one
SELECT id, user_id, name, device_type, firmware_version, battery_level, is_connected, active_eq_profile_id, paired_at, created_at, updated_at
FROM devices
WHERE id = $1
  AND user_id = $2
`

type GetDeviceByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDeviceByIDAndUser(ctx context.Context, arg GetDeviceByIDAndUserParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByIDAndUser, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.FirmwareVersion,
		&i.BatteryLevel,
		&i.IsConnected,
		&i.ActiveEqProfileID,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesByIDsAndUser = `-- name: ListDevicesByIDsAndUser :many
SELECT id, user_id, name, device_type, firmware_version, battery_level, is_connected, active_eq_profile_id, paired_at, created_at, updated_at
FROM devices
WHERE user_id = $1
  AND id = ANY($2::uuid[])
ORDER BY created_at DESC
`

type ListDevicesByIDsAndUserParams struct {
	UserID    pgtype.UUID   `json:"user_id"`
	DeviceIds []pgtype.UUID `json:"device_ids"`
}

func (q *Queries) ListDevicesByIDsAndUser(ctx context.Context, arg ListDevicesByIDsAndUserParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByIDsAndUser, arg.UserID, arg.DeviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceType,
			&i.FirmwareVersion,
			&i.BatteryLevel,
			&i.IsConnected,
			&i.ActiveEqProfileID,
			&i.PairedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, device_type, firmware_version, battery_level, is_connected, active_eq_profile_id, paired_at, created_at, updated_at
FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceType,
			&i.FirmwareVersion,
			&i.BatteryLevel,
			&i.IsConnected,
			&i.ActiveEqProfileID,
			&i.PairedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET
    name = $3,
    active_eq_profile_id = $4,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, device_type, firmware_version, battery_level, is_connected, active_eq_profile_id, paired_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID                pgtype.UUID `json:"id"`
	UserID            pgtype.UUID `json:"user_id"`
	Name              string      `json:"name"`
	ActiveEqProfileID pgtype.UUID `json:"active_eq_profile_id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ActiveEqProfileID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.FirmwareVersion,
		&i.BatteryLevel,
		&i.IsConnected,
		&i.ActiveEqProfileID,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
