// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eq_profiles.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomEQProfile = `-- name: CreateCustomEQProfile :one
INSERT INTO eq_profiles (
    owner_user_id,
    name,
    is_system,
    bands
)
VALUES ($1, $2, false, $3)
RETURNING id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
`

type CreateCustomEQProfileParams struct {
	OwnerUserID pgtype.UUID     `json:"owner_user_id"`
	Name        string          `json:"name"`
	Bands       json.RawMessage `json:"bands"`
}

func (q *Queries) CreateCustomEQProfile(ctx context.Context, arg CreateCustomEQProfileParams) (EqProfile, error) {
	row := q.db.QueryRow(ctx, createCustomEQProfile, arg.OwnerUserID, arg.Name, arg.Bands)
	var i EqProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsSystem,
		&i.Bands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const deleteCustomEQProfile = `-- name: DeleteCustomEQProfile :execrows
DELETE FROM eq_profiles
WHERE id = $1
  AND owner_user_id = $2
  AND is_system = false
`

type DeleteCustomEQProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteCustomEQProfile(ctx context.Context, arg DeleteCustomEQProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomEQProfile, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessibleEQProfile = `-- name: GetAccessibleEQProfile :one
SELECT id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
FROM eq_profiles
WHERE id = $1
  AND (is_system = true OR owner_user_id = $2)
`

type GetAccessibleEQProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetAccessibleEQProfile(ctx context.Context, arg GetAccessibleEQProfileParams) (EqProfile, error) {
	row := q.db.QueryRow(ctx, getAccessibleEQProfile, arg.ID, arg.OwnerUserID)
	var i EqProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsSystem,
		&i.Bands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getDefaultEQProfile = `-- name: GetDefaultEQProfile :one
SELECT id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
FROM eq_profiles
WHERE is_system = true
  AND is_default = true
`

func (q *Queries) GetDefaultEQProfile(ctx context.Context) (EqProfile, error) {
	row := q.db.QueryRow(ctx, getDefaultEQProfile)
	var i EqProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsSystem,
		&i.Bands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const listAccessibleEQProfiles = `-- name: ListAccessibleEQProfiles :many
SELECT id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
FROM eq_profiles
WHERE is_system = true OR owner_user_id = $1
ORDER BY
    is_system DESC,
    CASE WHEN is_system THEN is_default END DESC,
    CASE WHEN is_system THEN lower(name) END ASC,
    created_at DESC
`

func (q *Queries) ListAccessibleEQProfiles(ctx context.Context, ownerUserID pgtype.UUID) ([]EqProfile, error) {
	rows, err := q.db.Query(ctx, listAccessibleEQProfiles, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EqProfile{}
	for rows.Next() {
		var i EqProfile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.IsSystem,
			&i.Bands,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomEQProfiles = `-- name: ListCustomEQProfiles :many
SELECT id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
FROM eq_profiles
WHERE is_system = false
  AND owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCustomEQProfiles(ctx context.Context, ownerUserID pgtype.UUID) ([]EqProfile, error) {
	rows, err := q.db.Query(ctx, listCustomEQProfiles, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EqProfile{}
	for rows.Next() {
		var i EqProfile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.IsSystem,
			&i.Bands,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemEQProfiles = `-- name: ListSystemEQProfiles :many
SELECT id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
FROM eq_profiles
WHERE is_system = true
ORDER BY is_default DESC, lower(name) ASC
`

func (q *Queries) ListSystemEQProfiles(ctx context.Context) ([]EqProfile, error) {
	rows, err := q.db.Query(ctx, listSystemEQProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EqProfile{}
	for rows.Next() {
		var i EqProfile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.IsSystem,
			&i.Bands,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomEQProfile = `-- name: UpdateCustomEQProfile :one
UPDATE eq_profiles
SET
    name = $3,
    bands = $4,
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND is_system = false
RETURNING id, owner_user_id, name, is_system, bands, created_at, updated_at, is_default
`

type UpdateCustomEQProfileParams struct {
	ID          pgtype.UUID     `json:"id"`
	OwnerUserID pgtype.UUID     `json:"owner_user_id"`
	Name        string          `json:"name"`
	Bands       json.RawMessage `json:"bands"`
}

func (q *Queries) UpdateCustomEQProfile(ctx context.Context, arg UpdateCustomEQProfileParams) (EqProfile, error) {
	row := q.db.QueryRow(ctx, updateCustomEQProfile,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Bands,
	)
	var i EqProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsSystem,
		&i.Bands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}
