// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPartySessionDevice = `-- name: AddPartySessionDevice :execrows
INSERT INTO party_session_devices (
    party_session_id,
    device_id
)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1
    FROM party_sessions
    WHERE id = $1
      AND owner_user_id = $3
)
`

type AddPartySessionDeviceParams struct {
	PartySessionID pgtype.UUID `json:"party_session_id"`
	DeviceID       pgtype.UUID `json:"device_id"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) AddPartySessionDevice(ctx context.Context, arg AddPartySessionDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, addPartySessionDevice, arg.PartySessionID, arg.DeviceID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addPartySessionDevices = `-- name: AddPartySessionDevices :execrows
INSERT INTO party_session_devices (
    party_session_id,
    device_id
)
SELECT $1, input.device_id
FROM unnest($3::uuid[]) AS input(device_id)
WHERE EXISTS (
    SELECT 1
    FROM party_sessions
    WHERE id = $1
      AND owner_user_id = $2
)
`

type AddPartySessionDevicesParams struct {
	PartySessionID pgtype.UUID   `json:"party_session_id"`
	OwnerUserID    pgtype.UUID   `json:"owner_user_id"`
	DeviceIds      []pgtype.UUID `json:"device_ids"`
}

func (q *Queries) AddPartySessionDevices(ctx context.Context, arg AddPartySessionDevicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, addPartySessionDevices, arg.PartySessionID, arg.OwnerUserID, arg.DeviceIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPartySession = `-- name: CreatePartySession :one
INSERT INTO party_sessions (
    owner_user_id,
    name
)
VALUES ($1, $2)
RETURNING id, owner_user_id, name, status, started_at, ended_at, created_at, updated_at
`

type CreatePartySessionParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        pgtype.Text `json:"name"`
}

func (q *Queries) CreatePartySession(ctx context.Context, arg CreatePartySessionParams) (PartySession, error) {
	row := q.db.QueryRow(ctx, createPartySession, arg.OwnerUserID, arg.Name)
	var i PartySession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartySession = `-- name: DeletePartySession :execrows
DELETE FROM party_sessions
WHERE id = $1
  AND owner_user_id = $2
`

type DeletePartySessionParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeletePartySession(ctx context.Context, arg DeletePartySessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePartySession, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPartySessionByIDAndOwner = `-- name: GetPartySessionByIDAndOwner :one
SELECT
    ps.id, ps.owner_user_id, ps.name, ps.status, ps.started_at, ps.ended_at, ps.created_at, ps.updated_at,
    COALESCE(
        array_agg(psd.device_id ORDER BY psd.joined_at) FILTER (WHERE psd.device_id IS NOT NULL),
        ARRAY[]::uuid[]
    )::uuid[] AS device_ids
FROM party_sessions ps
LEFT JOIN party_session_devices psd ON psd.party_session_id = ps.id
WHERE ps.id = $1
  AND ps.owner_user_id = $2
GROUP BY ps.id
`

type GetPartySessionByIDAndOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

type GetPartySessionByIDAndOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        pgtype.Text        `json:"name"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeviceIds   []pgtype.UUID      `json:"device_ids"`
}

func (q *Queries) GetPartySessionByIDAndOwner(ctx context.Context, arg GetPartySessionByIDAndOwnerParams) (GetPartySessionByIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getPartySessionByIDAndOwner, arg.ID, arg.OwnerUserID)
	var i GetPartySessionByIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceIds,
	)
	return i, err
}

const listPartySessionDeviceIDs = `-- name: ListPartySessionDeviceIDs :many
SELECT psd.device_id
FROM party_session_devices psd
JOIN party_sessions ps ON ps.id = psd.party_session_id
WHERE psd.party_session_id = $1
  AND ps.owner_user_id = $2
ORDER BY psd.joined_at
`

type ListPartySessionDeviceIDsParams struct {
	PartySessionID pgtype.UUID `json:"party_session_id"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListPartySessionDeviceIDs(ctx context.Context, arg ListPartySessionDeviceIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPartySessionDeviceIDs, arg.PartySessionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var device_id pgtype.UUID
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartySessionsByOwner = `-- name: ListPartySessionsByOwner :many
SELECT
    ps.id, ps.owner_user_id, ps.name, ps.status, ps.started_at, ps.ended_at, ps.created_at, ps.updated_at,
    COALESCE(
        array_agg(psd.device_id ORDER BY psd.joined_at) FILTER (WHERE psd.device_id IS NOT NULL),
        ARRAY[]::uuid[]
    )::uuid[] AS device_ids
FROM party_sessions ps
LEFT JOIN party_session_devices psd ON psd.party_session_id = ps.id
WHERE ps.owner_user_id = $1
GROUP BY ps.id
ORDER BY ps.started_at DESC
`

type ListPartySessionsByOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        pgtype.Text        `json:"name"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeviceIds   []pgtype.UUID      `json:"device_ids"`
}

func (q *Queries) ListPartySessionsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]ListPartySessionsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listPartySessionsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartySessionsByOwnerRow{}
	for rows.Next() {
		var i ListPartySessionsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartySessionsByOwnerAndStatus = `-- name: ListPartySessionsByOwnerAndStatus :many
SELECT
    ps.id, ps.owner_user_id, ps.name, ps.status, ps.started_at, ps.ended_at, ps.created_at, ps.updated_at,
    COALESCE(
        array_agg(psd.device_id ORDER BY psd.joined_at) FILTER (WHERE psd.device_id IS NOT NULL),
        ARRAY[]::uuid[]
    )::uuid[] AS device_ids
FROM party_sessions ps
LEFT JOIN party_session_devices psd ON psd.party_session_id = ps.id
WHERE ps.owner_user_id = $1
  AND ps.status = $2
GROUP BY ps.id
ORDER BY ps.started_at DESC
`

type ListPartySessionsByOwnerAndStatusParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Status      string      `json:"status"`
}

type ListPartySessionsByOwnerAndStatusRow struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        pgtype.Text        `json:"name"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeviceIds   []pgtype.UUID      `json:"device_ids"`
}

func (q *Queries) ListPartySessionsByOwnerAndStatus(ctx context.Context, arg ListPartySessionsByOwnerAndStatusParams) ([]ListPartySessionsByOwnerAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listPartySessionsByOwnerAndStatus, arg.OwnerUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartySessionsByOwnerAndStatusRow{}
	for rows.Next() {
		var i ListPartySessionsByOwnerAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePartySessionDevice = `-- name: RemovePartySessionDevice :execrows
DELETE FROM party_session_devices psd
USING party_sessions ps
WHERE ps.id = psd.party_session_id
  AND ps.owner_user_id = $3
  AND psd.party_session_id = $1
  AND psd.device_id = $2
`

type RemovePartySessionDeviceParams struct {
	PartySessionID pgtype.UUID `json:"party_session_id"`
	DeviceID       pgtype.UUID `json:"device_id"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) RemovePartySessionDevice(ctx context.Context, arg RemovePartySessionDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removePartySessionDevice, arg.PartySessionID, arg.DeviceID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePartySession = `-- name: UpdatePartySession :one
UPDATE party_sessions
SET
    name = $3,
    status = $4,
    ended_at = CASE
        WHEN $4 = 'ended' THEN COALESCE(ended_at, now())
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
RETURNING id, owner_user_id, name, status, started_at, ended_at, created_at, updated_at
`

type UpdatePartySessionParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        pgtype.Text `json:"name"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdatePartySession(ctx context.Context, arg UpdatePartySessionParams) (PartySession, error) {
	row := q.db.QueryRow(ctx, updatePartySession,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Status,
	)
	var i PartySession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
