// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, language, notifications_enabled, created_at, updated_at
FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.NotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
    user_id,
    theme,
    language,
    notifications_enabled
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    theme = EXCLUDED.theme,
    language = EXCLUDED.language,
    notifications_enabled = EXCLUDED.notifications_enabled,
    updated_at = now()
RETURNING user_id, theme, language, notifications_enabled, created_at, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	Theme                string      `json:"theme"`
	Language             string      `json:"language"`
	NotificationsEnabled bool        `json:"notifications_enabled"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.NotificationsEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.NotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
