// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const convertGuestToRegistered = `-- name: ConvertGuestToRegistered :one
UPDATE users
SET
    role = 'registered',
    email = $2,
    password_hash = $3,
    display_name = COALESCE($4, display_name),
    converted_at = now()
WHERE id = $1
  AND role = 'guest'
RETURNING id, role, email, password_hash, display_name, created_at, converted_at
`

type ConvertGuestToRegisteredParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) ConvertGuestToRegistered(ctx context.Context, arg ConvertGuestToRegisteredParams) (User, error) {
	row := q.db.QueryRow(ctx, convertGuestToRegistered,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const createGuestUser = `-- name: CreateGuestUser :one
INSERT INTO users (role)
VALUES ('guest')
RETURNING id, role, email, password_hash, display_name, created_at, converted_at
`

func (q *Queries) CreateGuestUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createGuestUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const createRegisteredUser = `-- name: CreateRegisteredUser :one
INSERT INTO users (
    role,
    email,
    password_hash,
    display_name
)
VALUES ('registered', $1, $2, $3)
RETURNING id, role, email, password_hash, display_name, created_at, converted_at
`

type CreateRegisteredUserParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateRegisteredUser(ctx context.Context, arg CreateRegisteredUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createRegisteredUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1) AS exists
`

func (q *Queries) EmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, email, password_hash, display_name, created_at, converted_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, email, password_hash, display_name, created_at, converted_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, role, email, password_hash, display_name, created_at, converted_at
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ConvertedAt,
	)
	return i, err
}
